Apply last example_ynh
YunoHost-Apps/rocketchat_ynh pull request #123
Opened 2022-06-26 18:58 UTC by yalh76

## Problem

- *Fix #98*
- *Fix #94*
- *Fix #92*
- *Fix #89*

## Solution

- *Apply last example_ynh*
- *switching to ynh_mongo_db__2*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-06-26 18:58 UTC, yalh76 commented
!testme

2022-06-27 00:49 UTC, yalh76 commented
!testme

2022-06-28 17:38 UTC, yalh76 commented
!testme

2022-06-28 21:28 UTC, yalh76 commented
!testme

2022-06-29 17:57 UTC, ericgaspar requested changes

2022-06-29 17:57 UTC, ericgaspar commented on scripts/install
> +	ynh_exec_as $app env $ynh_node_load_PATH $ynh_npm install --unsafe-perm 2>/dev/null
```suggestion
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH $ynh_npm install --unsafe-perm
```

2022-06-29 17:57 UTC, ericgaspar commented on scripts/upgrade
> +	ynh_exec_as $app env $ynh_node_load_PATH npm install --unsafe-perm 2>/dev/null
```suggestion
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH npm install --unsafe-perm
```

2022-06-29 18:43 UTC, ericgaspar commented
Do we have to worry about those warnings in the remove script?

2022-06-30 06:33 UTC, yalh76 commented
> Do we have to worry about those warnings in the remove script?

Good catch, in the remove script L64 `$mongodb_servicename` is not initialized, I will correct that

2022-06-30 17:34 UTC, yalh76 commented
!testme

2022-07-01 00:45 UTC, yalh76 commented
!testme

2022-07-01 20:28 UTC, yalh76 commented
!testme

2022-07-02 16:12 UTC, yalh76 commented
@ericgaspar if you can have a look

2022-07-02 16:51 UTC, ericgaspar approved these changes
Thanks for your help! 👍

2022-07-02 16:52 UTC, merged